### ISSUE TITLE
Add documentation on how to run script on bastion

### ISSUE THREAD

**Issue by oboyle** [awslabs/amazon-guardduty-tester#12]
The documentation is missing the step where the scripts are run from the bastion host. It's kind of implied in the README, but I had to look through the script to figure out that it wasn't proxying through the bastion host.

I recommend adding a step to the README on the steps executed on the bastion host.

**Comment by scottbward** [comment]
Closing this issue.   The README provides guidance on how to connect to the bastion host and then be automatically forwarded to the actual EC2 instance where the test script will be run from.  There is no need to run any scripts from the actual bastion host.
