### ISSUE TITLE
Modify ProxyCommand to no longer use NetCat for proxied access to tester host

### ISSUE THREAD

**Issue by mlaruskiaws** [awslabs/amazon-guardduty-tester#19]
Instructions in README.md require use of NetCat with ProxyCommand ("ProxyCommand ssh bastion nc %h %p") this no longer works on the bastion host and results in an error.

[bash: nc <IP> <port>: command not found
kex_exchange_identification: Connection closed by remote host]

Instead, use the -W switch with OpenSSH ("ProxyCommand ssh -W %h:%p bastion").

For more information: https://unix.stackexchange.com/questions/317491/proxycommand-use-for-multiple-hops-and-prompt-authentication

**Comment by scottbward** [comment]
Closing this issue as this change has been made in the README.   Thanks for your input.
