### ISSUE TITLE
guardduty-tester.template fails due to`BastionAutoScalingGroup` 

### ISSUE THREAD

**Issue by ken5scal** [awslabs/amazon-guardduty-tester#2]
Running the template, I encountered a failure in CloudFormation-Stack because it failed to create `BastionAutoScalingGroup`. The error was `Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement`.

I tried to build the stack with the following parameters under the region ap-northeast-1:

```
VPCCIDR:  172.16.0.16/28
RemoteAccessCIDR: 0.0.0.0/0
PublicSubnetCIDR:172.16.0.0/28
PrivateSubnetCIDR: 172.16.0.16/28
AvailabilityZones: ap-northeast-1a
```

**Comment by ken5scal** [comment]
I recreated the stack, and it seems the AutoScalingGroup has created w/o  problem; however for some reason, the stack thinks it's failed and executes rollback.

![image](https://user-images.githubusercontent.com/9734362/42409409-0ec1b62a-8215-11e8-959f-e5f501072a8e.png)

**Comment by ken5scal** [comment]
I turned off `protection from delete` option and re-created the stack. It still fails but creates an instance `RedTeam`. However, I found that the instance has nothing in it required for running a test such as `guadduty_tester.sh`, `nmap` and so on.

**Comment by scottbward** [comment]
Closing this issue due to age.
