### ISSUE TITLE
Deployment via CloudFormation always fails

### ISSUE THREAD

**Issue by kasethi-aws** [awslabs/amazon-guardduty-tester#23]
Hi, have tried multiple accounts and regions, the template always fails to deploy as the CFN stack with some issue related to no healthy host response for ECSAutoScalingGroup - "Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE". 

Can someone please check if the template now doesn't work anymore and see if its possible to fix?

**Comment by scottbward** [comment]
I am aware of this issue and am actively looking into it.  I believe I will have a fix in the next day or two.  Thanks for reporting this.

**Comment by scottbward** [comment]
I have pushed an updated that addresses the failures with the ECSAutoScalingGroup.    thanks for reporting.
